// <auto-generated />
namespace Section4.BuildingAModelUsingCodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class initialModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202409051910073_initialModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
