//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section7.LoadingRelatedObjects
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Class <c>Course</c> create a new object with additional descriptive properties. 
    /// </summary>
    public partial class Course
    {
        /// <summary>
        /// Create an instance of Course object with Tags.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Tags = new HashSet<Tag>();
        }
        /// <summary>
        /// Gets or sets the Course Id.
        /// </summary>
        public int Id { get; set; }
        /// <summary>
        /// Gets or sets the Name.
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Gets or sets the Description.
        /// </summary>
        public string Description { get; set; }
        /// <summary>
        /// Gets or sets the Level.
        /// </summary>
        public int Level { get; set; }
        /// <summary>
        /// Gets or sets the Full Price.
        /// </summary>
        public float FullPrice { get; set; }
        /// <summary>
        /// Gets or sets the Author Id.
        /// </summary>
        public int AuthorId { get; set; }

        /// <summary>
        /// Gets or sets the Author.
        /// </summary>
        public virtual Author Author { get; set; }
        /// <summary>
        /// Gets or sets the Cover.
        /// </summary>
        public virtual Cover Cover { get; set; }
        /// <summary>
        /// Gets or sets the Tags.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
