//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section7.LoadingRelatedObjects
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Class <c>Cover</c> create a new object with additional descriptive properties. 
    /// </summary>
    public partial class Cover
    {
        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        public int Id { get; set; }
    
        /// <summary>
        /// Gets or sets Course.
        /// </summary>
        public virtual Course Course { get; set; }
    }
}
