//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Section7.LoadingRelatedObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    /// <summary>
    /// Class <c>Pluto_QueriesEntities</c> is an object representing the database "Pluto_Queries".
    /// </summary>
    public partial class Pluto_QueriesEntities : DbContext
    {
        /// <summary>
        /// Create an instance of Pluto_QueriesEntities object with all entities.
        /// </summary>
        public Pluto_QueriesEntities()
            : base("name=Pluto_QueriesEntities")
        {   //Lazy Loading is turned off if LazyLoadingEnable is set to false;
            Configuration.LazyLoadingEnabled = true;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        /// <summary>
        /// Table Authors in the database "Pluto_Queries".
        /// </summary>
        public virtual DbSet<Author> Authors { get; set; }
        /// <summary>
        /// Table Courses in the database "Pluto_Queries".
        /// </summary>
        public virtual DbSet<Course> Courses { get; set; }
        /// <summary>
        /// Table Covers in the database "Pluto_Queries".
        /// </summary>
        public virtual DbSet<Cover> Covers { get; set; }
        /// <summary>
        /// Table Tags in the database "Pluto_Queries".
        /// </summary>
        public virtual DbSet<Tag> Tags { get; set; }
    }
}
