//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    /// <summary>
    /// Class <c>DbFirstDemoEntities</c> is an object representing the database "DbFirstDemo".
    /// </summary>
    public partial class DbFirstDemoEntities : DbContext
    {
        /// <summary>
        /// Create a new instance of DbFirstDemoEntities.
        /// </summary>
        public DbFirstDemoEntities()
            : base("name=DbFirstDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// Table Posts in the database "DbFirstDemo".
        /// </summary>
        public virtual DbSet<Post> Posts { get; set; }
    }
}
