//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Class <c>CourseSection</c> create a new object with additional descriptive properties. 
    /// </summary>
    public partial class CourseSection
    {
        /// <summary>
        /// Gets or sets the Section Id.
        /// </summary>
        public int SectionID { get; set; }
        /// <summary>
        /// Gets or sets the Course Id.
        /// </summary>
        public int CourseID { get; set; }
        /// <summary>
        /// Gets or sets the Title.
        /// </summary>
        public string Title { get; set; }   
        /// <summary>
        /// Gets or sets the Course.
        /// </summary>
        public virtual Course Course { get; set; }
    }
}
