//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirst
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Class <c>tblUser</c> create a new object with additional descriptive properties. 
    /// </summary>
    public partial class tblUser
    {
        /// <summary>
        /// Gets or sets a User Id.
        /// </summary>
        public int UserID { get; set; }
        /// <summary>
        /// Gets or sets the Username.
        /// </summary>
        public string Username { get; set; }
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        public int Password { get; set; }
    }
}
